#!/usr/bin/python2.7

import argparse
import os
import sys
import subprocess
import textwrap

def main():

    # Redefine the exception handling routine so that it does NOT
    # do a trace dump if the user types ^C while lsseq is running.
    #
    old_excepthook = sys.excepthook
    def new_hook(exceptionType, value, traceback):
        if exceptionType != KeyboardInterrupt and exceptionType != IOError:
            old_excepthook(exceptionType, value, traceback)
        else:
            pass
    sys.excepthook = new_hook

    p = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent('''\
            Print the times table up to n by n.
            '''),
        usage="%(prog)s [OPTION]...")

    p.add_argument("--version", action="version", version="0.100")
    p.add_argument("--size", "-n", action="store", type=int, dest="n",
        default=13, metavar="N",
	help="The size of the multiplication table (default=13).")
    p.add_argument("--primes", action="store_true",
        dest="onlyPrimes", default=False,
        help="only print out the multiplication table for prime numbers" )
    p.add_argument("--limit", action="store", type=int, dest="maxDigits",
        default=-1, metavar="MAX",
	help="Limit printing the table to numbers of length MAX-digits or less")

    args = p.parse_args()

    if args.n < 2 :
	if args.n == 1 :
	    print " * | 1"
	    print "---+---"
	    print " 1 | 1"
        sys.exit(0)

    if args.maxDigits == 0 :
        print >> sys.stderr, os.path.basename(sys.argv[0]) + \
            ": warning: max digits is 0, nothing to print."
        sys.exit(0)

    # Note: this "isPrime" array will be filled with True 
    # in the case that we want to display ALL the integers
    # from 2,n - sorry, it's a bit of a cheat to use this list
    # this way, but it makes for clean code.
    #
    isPrime = [True]*(args.n+1)

    # Sieve of Eratosthenes - skipped when wanting to list ALL numbers
    #
    if args.onlyPrimes : 
	p = 2
	while p < (args.n / 2) :
	    i = 2
	    while p*i <= args.n :
		isPrime[p*i] = False
		i += 1
	    p += 1
	    while not isPrime[p] :
		p += 1

    # Find the largest prime in table
    #
    if not args.onlyPrimes :
	maxN = args.n
    else :
	i = len(isPrime)
	i -= 1
	while not isPrime[i] : 
	    i -= 1
	maxN = i

    # If maxDigits is set then the biggest number in the table has
    # to be (99...9-1)/2 since (99...9+1)/2 * 2 (the slowest growing
    # set of entries in the table are the twos) is one digit too long!
    #
    intFormat = "{:d}"
    if args.maxDigits > 0 :
	x = (int('9'*args.maxDigits)-1)/2
	if x < maxN :
	    maxN = x


    outputLine = ""
    formatList = [0]
    commaFormat = "{:>,d}"
    prettyMaxLen = 0
    if args.maxDigits > 0 :
	prettyMaxLen = len(commaFormat.format(int("9"*args.maxDigits)))
    n = 1
    while n <= maxN :
	x = n * maxN
	sPretty = commaFormat.format(x)
	sInt = intFormat.format(x)

	if args.maxDigits > 0 :
	    if len(sInt) <= args.maxDigits :
		formatList.append(len(sPretty))
	    else :
		formatList.append(prettyMaxLen)
	else :
	    formatList.append(len(sPretty))

	commaFormatPad = "{:>"+ str(formatList[-1]) + ",d}"
	outputLine += commaFormatPad.format(n)
	if n == 1 :
	    outputLine = outputLine.replace("1", "*")
	    outputLine += " | "
	else :
	    outputLine += "  "
	n += 1

    # Make the horizontal dividing line of the table
    #
    dividingLine = "-"*len(outputLine)
    s = list(dividingLine)
    s[formatList[1] + 1] = '+'

    # Print 2...n on the first row then the dividing line.
    #
    print outputLine
    print "".join(s)

    # Print the multiplication table.
    #
    n = 2
    while n <= maxN :
	commaFormatPad = "{:>"+ str(formatList[1]) + ",d}"
	outputLine = commaFormatPad.format(n) + " | "
        m = 2
	if isPrime[n] :
	    while m <= maxN :
		x = n * m
		commaFormatPad = "{:>"+ str(formatList[m]) + ",d}"
		if args.maxDigits > 0 :
		    if len(intFormat.format(x)) <= args.maxDigits :
			outputLine += commaFormatPad.format(x) + "  "
		    else :
			break
		else :
		    outputLine += commaFormatPad.format(x) + "  "
		m += 1
	    print outputLine
        n += 1
        
if __name__ == '__main__':
    main()
